# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AMoAdAdMobDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#  pod 'Google-Mobile-Ads-SDK'
  # Pods for AMoAdAdMobDemo

  target 'AMoAdAdMobDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AMoAdAdMobDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
